### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by chopmann** [akoch/gitlab-mylyn-connector#1]
Are you still working on this?

**Comment by akoch** [comment]
Hey, 
sorry for the late answer. Yes. I'm stil working on this. In fact, I have (and use) a version that fits my personal needs. So perhaps I just should push it here.

**Comment by chopmann** [comment]
That would be great!

**Comment by chopmann** [comment]
@akoch Dont want to be rude, but dont forget me :wink:

**Comment by Isammoc** [comment]
I am also interested

**Comment by RdeWilde** [comment]
Push it to the community? Even if instable, it's better than nothing.

**Comment by mcgivrer** [comment]
Hey, I think that a lot of people would be interested in using such integration tool ! 
Do you need any help on this dev ?

Please, share it to make us work/fork on such piece of software ;)

**Comment by chopmann** [comment]
@akoch Think lot's of people would be glad to help..myself included! :)

**Comment by pweingardt** [comment]
I developed a Connector myself, if anyone wants to check it out, its on github:

https://github.com/pweingardt/mylyn-gitlab
